name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Stop Old Container if running
      run: sudo docker stop flask-container || true
    - name: Delete Old docker container
      run: sudo docker rm flask-container || true
    - name: Delete Old docker Image
      run: sudo docker rmi $(sudo docker images -q) || true
    - name: Pull Docker image
      run: sudo docker pull 316usman/flask-app:latest
    - name: Run Docker Container
      run: sudo docker run -d -p 4000:4000 --name flask-container -e DB_USERNAME="admin" -e DB_PASSWORD="password" -e DB_HOST="mysql.cnxaskfqnbak.us-east-1.rds.amazonaws.com" -e DB_NAME="mydb" 316usman/flask-app:latest

