name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t 316usman/flask-app:latest .
          docker push 316usman/flask-app:latest

      # - name: SSH to EC2 and deploy
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_KEY }}
      #     debug: true
      #     port: 22
      #     script: |
      #       docker pull 316usman/flask-app:latest
      #       docker stop flask-container || true
      #       docker rm flask-container || true
      #       docker run -d -p 4000:4000 --name flask-container 316usman/flask-app:latest
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.6.0

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_KEY }}

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-command@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          script: |
            docker pull 316usman/flask-app:latest
            docker stop flask-container || true
            docker rm flask-container || true
            docker run -d -p 4000:4000 --name flask-container 316usman/flask-app:latest
